/*
https://opensource.org/license/bsl-1-0

Permission is hereby granted, free of charge, to any person or
organization obtaining a copy of the software and accompanying
documentation covered by this license (the “Software”) to use,
reproduce, display, distribute, execute, and transmit the Software,
and to prepare derivative works of the Software, and to permit
third-parties to whom the Software is furnished to do so, all subject
to the following:

The copyright notices in the Software and this entire statement,
including the above license grant, this restriction and the following
disclaimer, must be included in all copies of the Software, in whole
or in part, and all derivative works of the Software, unless such
copies or derivative works are solely in the form of
machine-executable object code generated by a source language
processor.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND
NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE
DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER
LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <stdint.h>
#include <inttypes.h>

#include "get_time.h"

static int process_array(char* p,unsigned repeats, unsigned blocks) {
	char* cp;
	int sum = 0;
	size_t _, j;

	for (_ = 0; _ < repeats; ++_) {
		cp = p;
		// If original p is aligned to a cache line, we access cache
		// lines #0, #3, #6, #9 etc. Because 2^n is not devided by 3,
		// sooner or later we use entire cache level-1.
		//
		// If, on the other hand, p is cache line offset + (CACHE_LINE/2),
		// we access cache lines #0, #1, #3, #4, #6, #7, #9, #10 etc.
		// etc. That is, we access twice as many cache lines.
		// What we measure here is a performance penalty of this.
		for (j = 0; j < blocks; ++j) {
			sum += cp[0];

			// access current or next cache line depending on p alignment
			sum += cp[CACHE_LINE / 2];

			cp += CACHE_LINE * 3;
		}
	}

	return sum;
}

static void usage(void) {
	printf("usage: cache_line_test [cache_size] [repeat] [offset]\n");
}

int main(int argc, char** argv) {
	--argc; ++argv;
	if (argc != 3) {
		usage();
		return 1;
	}

	unsigned cache_size = atoi(argv[0]);
	unsigned repeats = atoi(argv[1]);
	unsigned offset = atoi(argv[2]);

	char* p = aligned_alloc(CACHE_LINE, cache_size * 3);
	memset(p, -2, cache_size * 3);

	int sum;

	uint64_t begin = user_time();
	sum = process_array(p + offset, repeats, cache_size / CACHE_LINE);
	printf("time: %" PRId64 " millisecs (sum: %d)\n", (user_time() - begin) / 1000, sum);

	return 0;
}
